# Generated by Django 4.1.1 on 2022-09-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_rename_full_name_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("STUDENT", "student"),
                    ("LECTURER", "Lecturer"),
                ],
                max_length=100,
            ),
        ),
    ]
