# Generated by Django 4.1.1 on 2022-09-27 15:21

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("base.user",),
            managers=[
                ("students", django.db.models.manager.Manager()),
            ],
        ),
    ]
